/*
 *  Module :Ultrasonic sensor
 *	File name: ultrasonic_sensor.h
 *  Created on: Oct 11, 2021
 *  Author: osama
 */

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/* Configurations  */
#define ULTRASONIC_TRIGGER_PORT			PORTB_ID
#define ULTRASONIC_ECHO_PORT			PORTD_ID
#define TRIG_PIN						5
#define ECHO_PIN						6
#define TRIGGER_PULSE_DURATION			10


/* Functions prototypes */

/*	Function description:
 	Initialize the ICU driver as required.
	Setup the ICU call back function.
	Setup the direction for the trigger pin as output pin through the GPIO driver.
 * */
void ultrasonic_init(void);


/*	Function description:
 * 	Send the Trigger pulse to the ultrasonic sensor
 * */
void ultrasonic_Trigger(void);


/*
 * Function description:
	Send the trigger pulse by using Ultrasonic_Trigger function.
	Start the measurements by the ICU from this moment.
 * */
uint16 ultrasonic_readDistance(void);

/*
 * Function description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 * */
void ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_SENSOR_H_ */
